name: better_widget_flutter
description: "A better version of widget but still use other widget for Flutter"
version: 0.0.3
homepage:

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.17
  toastification: ^2.3.0
  get: ^4.6.6
  animate_do: ^3.3.6
  easy_animate: ^0.0.3
  cached_network_image: ^3.4.1
  flutter_cache_manager: ^3.4.1
  modal_bottom_sheet: ^3.0.0
  photo_view: ^0.15.0
  smooth_page_indicator: ^1.2.0+3
  infinite_scroll_pagination: ^4.1.0
  better_utils_flutter:
    git: https://github.com/Virakyuth-PK/better_utils_flutter.git
    version: 0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
